/**
 * Gemini Service (Public Interface)
 * Now independently connects to Google Gemini APIs, with fallback capabilities
 */
import { GoogleGenerativeAI } from "@google/generative-ai";
import { ExplanationRequest, Application } from '../types';
import * as HuggingFaceService from './huggingFaceService';

const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
const genAI = apiKey ? new GoogleGenerativeAI(apiKey) : null;

export interface BulkAnalysisRequest {
  studentName: string;
  studentSkills: string[];
  studentCgpa: number;
  rejections: Array<{
    jobRole: string;
    jobCompany: string;
    jobRequiredSkills: string[];
    jobMinCgpa: number;
    rejectionDate?: string;
  }>;
}

export interface PatternAnalysis {
  commonMissingSkills: Array<{ skill: string; frequency: number }>;
  cgpaIssues: boolean;
  improvementPriorities: string[];
  industryInsights: string;
  progressTracking?: {
    previousAnalysisDate?: string;
    improvementsSince?: string[];
  };
}

export interface RejectionAnalysis {
  coreMismatch: string;
  keyMissingSkills: string[];
  resumeFeedback: string[];
  actionPlan: string[];
  sentiment: string;
  type?: 'RULE_BASED' | 'NON_RULE_BASED';
  violations?: Array<{category: string, description: string, expected: string, actual: string}>;
  skillGaps?: Array<{skill: string, required: string, studentLevel?: string, suggestion: string}>;
  improvementSuggestions?: string[];
}

export const generateRejectionExplanation = async (
  data: ExplanationRequest,
  userId: string = 'anonymous'
): Promise<RejectionAnalysis> => {
  if (!genAI) {
    console.warn("VITE_GEMINI_API_KEY is missing. Falling back to HuggingFace / Mock logic.");
    return HuggingFaceService.generateRejectionExplanation(data, userId);
  }

  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const prompt = `You are an expert career coach. Analyze this rejection to provide actionable feedback in JSON format.
      Job: ${data.jobRole} at ${data.jobCompany}
      Candidate Skills: ${data.skillConfidenceData?.map(s => s.name).join(', ')}
      Required Skills: ${data.jobRequiredSkills?.join(', ')}
      Ensure response is ONLY valid JSON with keys: "coreMismatch", "keyMissingSkills" (array), "resumeFeedback" (array), "actionPlan" (array), "sentiment" (text). 
      No markdown formatting in response.`;

    const result = await model.generateContent(prompt);
    const text = result.response.text().replace(/`{3}json|`{3}/g, '');
    return JSON.parse(text) as RejectionAnalysis;
  } catch (error) {
    console.error("Gemini API Error, falling back to HF:", error);
    return HuggingFaceService.generateRejectionExplanation(data, userId);
  }
};

export const generateBulkRejectionAnalysis = async (
  data: BulkAnalysisRequest,
  userId: string = 'anonymous'
): Promise<PatternAnalysis> => {
  return HuggingFaceService.generateBulkRejectionAnalysis(data, userId);
};

export const formatAnalysisForExport = (
  studentName: string,
  analysis: string,
  application: { role: string; company: string },
  date: string = new Date().toLocaleDateString()
): string => {
  return `
═══════════════════════════════════════════════════════
           WHYNOT - AI REJECTION ANALYSIS REPORT
═══════════════════════════════════════════════════════

Student: ${studentName}
Position: ${application.role}
Company: ${application.company}
Analysis Date: ${date}

───────────────────────────────────────────────────────
                    DETAILED ANALYSIS
───────────────────────────────────────────────────────

${analysis}

───────────────────────────────────────────────────────
                  GENERATED BY GEMINI AI
───────────────────────────────────────────────────────
  `.trim();
};

export const analyzeResume = async (
  resumeText: string,
  targetRole: string = 'General',
  userId: string
): Promise<any> => {
  if (!genAI) {
    console.warn("VITE_GEMINI_API_KEY is missing. Falling back to HuggingFace / Mock logic.");
    return HuggingFaceService.analyzeResume(resumeText, targetRole, userId);
  }

  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const prompt = `Analyze this resume for ${targetRole}. Return strictly valid JSON containing:
    "overallScore" (number), "sectionScores" (array of objects with name, score, feedback, strengths, improvements), "keywordAnalysis" (found, missing arrays), "atsAnalysis" (score, issues, tips arrays), "actionableAdvice" (array).
    Resume: ${resumeText.substring(0, 2000)}`;

    const result = await model.generateContent(prompt);
    const text = result.response.text().replace(/`{3}json|`{3}/g, '');
    return JSON.parse(text);
  } catch (error) {
    console.error("Gemini API Error, falling back to HF:", error);
    return HuggingFaceService.analyzeResume(resumeText, targetRole, userId);
  }
};

export const generateResumeSuggestions = (analysisData: any): string[] => {
  const suggestions: string[] = [];
  if (analysisData.overallScore < 60) {
    suggestions.push('🔴 Overall resume needs significant improvement. Focus on high-priority items.');
  } else if (analysisData.overallScore < 80) {
    suggestions.push('🟡 Good foundation, but areas need refinement.');
  } else {
    suggestions.push('🟢 Strong resume! Minor tweaks will make it excellent.');
  }
  
  if (analysisData.atsAnalysis?.score < 70) {
    suggestions.push(`⚠️ ATS Score: ${analysisData.atsAnalysis.score}/100 - May not pass screening`);
  }
  return suggestions;
};
